version: '3.8'

services:
  app:
    build: ./fastAPI
    container_name: fastAPI
    ports:
      - "${PORT}:80"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./fastAPI/src/data:/app/src/data
      - ./fastAPI/src/templates:/app/src/templates
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
     
  adminer:
    #build: ./adminer
    image: adminer:latest
    container_name: adminer_container
    environment:
      ADMINER_SERVER: db
      ADMINER_USERNAME: ${POSTGRES_USER}
      ADMINER_DB: ${POSTGRES_DB}
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  postgres-data: